{% set name = "pythainlp" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pythainlp-{{ version }}.tar.gz
  sha256: 04c6e4bdd806204be742f139b1f2e666411c4509c270dfff1a8b5afa69d36d2b

build:
  number: 0
  noarch: python
  entry_points:
    - thainlp = pythainlp.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - python-tzdata  # [win]
    - requests >=2.31
    - __unix  # [unix]
    - __win   # [win]

test:
  imports:
    - pythainlp
  commands:
    - pip check
    - thainlp --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/PyThaiNLP/pythainlp
  summary: Thai Natural Language Processing library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - shermansiu
