{% set name = "pythainlp" %}
{% set version = "5.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pythainlp-{{ version }}.tar.gz
  sha256: 9018388f1d0c8ef66838dd1662e1369713c31a7d3efa27cc31d36d259969045d

build:
  number: 0
  noarch: python
  entry_points:
    - thainlp = pythainlp.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - python-tzdata  # [win]
    - numpy >=1.22
    - pandas >=0.24
    - pyyaml >=5.4.1
    - requests >=2.31
    - __unix  # [unix]
    - __win   # [win]

test:
  imports:
    - pythainlp
  commands:
    - pip check
    - thainlp --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/PyThaiNLP/pythainlp
  summary: Thai Natural Language Processing library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - shermansiu
