{% set name = "pythainlp" %}
{% set version = "5.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pythainlp-{{ version }}.tar.gz
  sha256: 516c34d22689c2b469dd74bb18221eb9336e42f5137aa32940008293f1895de4

build:
  number: 0
  noarch: python
  entry_points:
    - thainlp = pythainlp.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - python-tzdata  # [win]
    - numpy >=1.22
    - pandas >=0.24
    - pyyaml >=5.4.1
    - requests >=2.31
    - __unix  # [unix]
    - __win   # [win]

test:
  imports:
    - pythainlp
  commands:
    - pip check
    - thainlp --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/PyThaiNLP/pythainlp
  summary: Thai Natural Language Processing library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - shermansiu
